#!/bin/bash

# Function to query and display DNS information for a subdomain
get_dns_info() {
    subdomain="$1.$2"
    result=$(dig $subdomain | awk '/ANSWER SECTION:/ {getline; print}')
    if [ -z "$result" ]; then
        echo "The subdomain $subdomain does not exist."
    else
        ip_address=$(echo $result | awk '{print $NF}')
        record_type=$(echo $result | awk '{print $(NF-1)}')
        echo "The subdomain $1 is a $record_type record and points to $ip_address"
    fi
}

# Main script
if [ $# -eq 0 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"

if [ $# -eq 1 ]; then
    # Display information for default subdomains
    get_dns_info "www" "$domain"
    get_dns_info "lb-01" "$domain"
    get_dns_info "web-01" "$domain"
    get_dns_info "web-02" "$domain"
else
    # Display information for the specified subdomain
    subdomain="$2"
    get_dns_info "$subdomain" "$domain"
fi

